#!/bin/bash
#SBATCH -J C103_merge
#SBATCH -p red
#SBATCH -t 200:00:00
#SBATCH --ntasks=1
#SBATCH -o /latticeQCD/raid1/ahanlon/data/C103/to_sigmond.log
#SBATCH -e /latticeQCD/raid1/ahanlon/data/C103/to_sigmond.err
#SBATCH --mail-user=ddhanlon@gmail.com

#export  PATH=$PATH:/usr/local/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

PYTHON=/home/ahanlon/.apps/python/3.9.0/bin/python3.9
PROG=/home/ahanlon/code/sigmond_scripts/data_conversion/C103/to_sigmond.py
INPUTDIR=/latticeQCD/raid1/ahanlon/data/C103/raw/
OUTPUTDIR=/latticeQCD/raid1/ahanlon/data/C103/merged/

${PYTHON} ${PROG} -i ${INPUTDIR} -o ${OUTPUTDIR}
